codecov: 
  token: b86d51b5-9e2f-4502-b289-9534575c34d3
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        
  ignore:
    - "PyGame_Project/MVC/View_GUI/"
    - "*/View_CLI/*"
    - "*/View_GUI/*"
    - "*/__main__.py"

comment:
  layout: "diff, flags, files"
  behavior: update
  require_changes: false
