codecov: 
 token: b86d51b5-9e2f-4502-b289-9534575c34d3
 require_ci_to_pass: yes

coverage:
  round: down
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
        flags:
          - unittests
        if_ci_failed: error
        if_not_found: error
        if_no_data: error

comment:
  layout: "diff, flags, files"
  behavior: update
  require_changes: false
