codecov: 
  token: b86d51b5-9e2f-4502-b289-9534575c34d3
  require_ci_to_pass: yes

ignore:
  - "**/View_CLI"
  - "**/View_GUI"
  - "**/PyGame_Project/__main__.py"

coverage:
  round: down
  status:
    project:
      default:
        target: auto
        threshold: 0%


comment:
  layout: "diff, flags, files"
  behavior: update
  require_changes: false
