# This workflow will install Python dependencies, run tests and lint with a Python 3.11
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Unit Testing

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test with pytest
      run: |
        pytest -ra PyGame_Project/Test/ -v
    
    - name: Generate coverage report
      run: |
        pip install codecov
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml        
        codecov
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with: 
        fail_ci_if_error: true
        verbose: true
        flags: unittests
        target: auto
        token: ${{ secrets.CODECOV_TOKEN }}
